# Generated by Django 4.0 on 2021-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_users_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
