# Generated by Django 4.0 on 2021-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_users_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='approval',
            field=models.CharField(choices=[('2', 'Pending'), ('1', 'Approved'), ('3', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
