# Generated by Django 4.0 on 2021-12-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
