# Generated by Django 4.0 on 2021-12-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_booking_user_alter_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.FileField(default='assets/img/user3.png', upload_to='dp'),
        ),
    ]
